#!/bin/sh

CMD_LOG_FILE=command-list-file-`date`.log
CLUSTER_LIST_FILE=cluster-list

max=17000
i=15000
while [ $i -lt $max ] 
do
    run_filename=/data/ucnadata/2010/rootfiles/full$i.root
    if [ -r $run_filename ] 
    then
        echo "analyzing $run_filename..."
        echo "./pd_led_pmt_analysis $i" >> $CMD_LOG_FILE
    else
        echo "slipping $run_filename..."
    fi
    i=`expr $i + 1`
done

if [ -f $CLUSTER_LIST_FILE ]
then
    nice -n10 parallel --sshloginfile $CLUSTER_LIST_FILE < $CMD_LOG_FILE
else
    nice -n10 parallel < $CMD_LOG_FILE
fi

